export const RESUME = {
  name: "Ganapathi Kakarla",
  title: "AI & Data Science",
  tagline: "Bridging Healthcare & Artificial Intelligence",
  summary:
    "Cardiac Care & Cardiovascular Technology graduate, currently pursuing PGDM in AI & Data Science in Healthcare. Passionate about how AI and data-driven technologies create impact across industries. With a foundation in medical sciences and growing skills in Machine Learning, Data Analysis, and AI innovation — bridging the gap between technology and real-world problem-solving.",
  objective:
    "Technical professional focused on applying data analysis, machine learning, and business intelligence to support strategic decisions and AI innovation in healthcare.",
  email: "kakarlagana18@gmail.com",
  socials: {
    linkedin: "https://www.linkedin.com/in/ganapathi-kakarla-ai-data-science",
    github: "https://github.com/ganapathi-ai",
    credly: "https://www.credly.com/users/ganapathi-kakarla",
    orcid: "https://orcid.org/0009-0003-1251-6581",
  },
  languages: [
    { lang: "English", level: "Professional" },
    { lang: "Telugu", level: "Fluent" },
    { lang: "Hindi", level: "Beginner" },
  ],
  education: [
    {
      degree: "PGDM – AI & Data Science in Healthcare",
      institution: "IIHMR, Bangalore",
      year: "June 2025 – June 2027",
      score: "",
    },
    {
      degree: "B.Sc Cardiovascular Technology",
      institution: "NTR University of Health Sciences",
      year: "March 2021 – April 2025",
      score: "70.2%",
    },
    {
      degree: "Intermediate Education",
      institution: "Sri Chaitanya Junior College, Vijayawada",
      year: "June 2016 – March 2018",
      score: "96.6%",
    },
    {
      degree: "10th Class",
      institution: "Andhra Pradesh Residential School",
      year: "March 2016",
      score: "92.15%",
    },
  ],
  experience: [
    {
      role: "LLM Post Training Intern",
      company: "Ethara AI",
      location: "Gurugram (Remote)",
      period: "Feb 2026 – Present",
      duration: "3 months",
      active: true,
      tags: ["LLM", "NLP", "Post-Training", "AI"],
      desc: "Working on large language model post-training pipelines including data annotation, RLHF, and model evaluation.",
    },
    {
      role: "Data Science Intern",
      company: "Unified Mentor",
      location: "Remote",
      period: "Jan 2026 – Present",
      duration: "Ongoing",
      active: true,
      tags: ["Python", "ML", "EDA", "Streamlit"],
      desc: "Building end-to-end data science projects spanning healthcare analytics, forecasting, and ML model deployment.",
    },
    {
      role: "AI Intern",
      company: "Clinchbridge",
      location: "Remote",
      period: "Jan 2026 – Feb 2026",
      duration: "2 months",
      active: false,
      tags: ["AI", "Deep Learning"],
      desc: "Contributed to AI research and development projects in a fast-paced startup environment.",
    },
    {
      role: "Cardiovascular Technical Intern",
      company: "KIMS Hospitals",
      location: "Srikakulam, Andhra Pradesh",
      period: "Apr 2024 – Apr 2025",
      duration: "1 year 1 month",
      active: false,
      tags: ["ECG", "Holter Monitoring", "Echocardiography", "TEE", "TMT", "Cath Lab"],
      desc: "Hands-on clinical experience in ECG, Holter monitoring, echocardiography, TEE, treadmill test, and catheterization lab procedures.",
    },
    {
      role: "Student Intern",
      company: "KIMS-Sunshine Hospitals",
      location: "Rasoolpura, Hyderabad, Telangana",
      period: "Oct 2023 – Dec 2023",
      duration: "3 months",
      active: false,
      tags: ["Cardiology", "Echo", "Holter", "TMT"],
      desc: "Clinical training in cardiovascular diagnostics including echocardiography, TMT, and holter monitoring.",
    },
    {
      role: "Cardiovascular Technology Intern",
      company: "Great Eastern Medical School & Hospital",
      location: "Srikakulam, Andhra Pradesh",
      period: "Jun 2021 – Sep 2023",
      duration: "2 years 4 months",
      active: false,
      tags: ["Catheterization", "Echocardiography", "TMT", "Holter"],
      desc: "Foundational clinical training in catheterization, echocardiography, TMT, echo, and holter monitoring over 2+ years.",
    },
  ],
  projects: [
    {
      icon: "📊",
      title: "Care Transition Efficiency Analytics",
      desc: "End-to-end analytics for UAC reunification pipeline — CBP custody, HHS care, and sponsor placement outcomes for the U.S. Dept. of Health and Human Services.",
      tags: ["Python", "Streamlit", "Power BI", "EDA"],
      category: "Analytics",
      github: "https://github.com/ganapathi-ai/uac-care-transition-analytics",
    },
    {
      icon: "🩺",
      title: "Diabetic Foot Ulcer Segmentation",
      desc: "CNN model using ResNet34 + U-Net architecture with advanced augmentation for precise diabetic foot ulcer image segmentation.",
      tags: ["Deep Learning", "ResNet34", "U-Net", "CNN"],
      category: "Deep Learning",
      github: null,
    },
    {
      icon: "❤️",
      title: "Heart Attack Risk Analysis",
      desc: "Interactive Tableau dashboard analyzing heart attack risk factors and identifying high-risk patient profiles. Explores relationships between demographic attributes and clinical risk indicators.",
      tags: ["Tableau", "Healthcare", "Visualization"],
      category: "Analytics",
      github: null,
    },
    {
      icon: "🏥",
      title: "Health Insurance Claims Dashboard",
      desc: "End-to-end analytical Power BI view of health insurance claims — financial trends, provider performance, and demographic patterns for cost optimization.",
      tags: ["Power BI", "Analytics", "Finance"],
      category: "Analytics",
      github: null,
    },
    {
      icon: "🏨",
      title: "Healthcare Operations Dashboard",
      desc: "Power BI report analyzing healthcare operational performance and supporting data-driven decision-making across hospital and clinical environments.",
      tags: ["Power BI", "Healthcare Ops", "Analytics"],
      category: "Analytics",
      github: "https://github.com/ganapathi-ai/Healthcare-Operations-Dashboard--POWER-BI",
    },
    {
      icon: "👶",
      title: "Fetal Health Classification",
      desc: "ML model classifying fetal health using CTG data with real-time Streamlit clinical prediction app for early risk detection.",
      tags: ["Machine Learning", "Streamlit", "CTG"],
      category: "ML",
      github: null,
    },
    {
      icon: "🔬",
      title: "Survival Analysis – VAP Prevention",
      desc: "Kaplan–Meier & Cox regression on ICU trial data evaluating chlorhexidine effectiveness for ventilator-associated pneumonia prevention.",
      tags: ["Python", "Kaplan-Meier", "Cox Regression"],
      category: "Analytics",
      github: null,
    },
    {
      icon: "🫀",
      title: "EchoLens – AI Echocardiogram Reporting",
      desc: "AI-assisted reporting system reducing manual echocardiography time with ASE-compliant structured reporting and UX research validation.",
      tags: ["Healthcare AI", "UX Research", "ASE"],
      category: "AI",
      github: null,
    },
    {
      icon: "🧬",
      title: "Prostate Cancer Outcome Prediction",
      desc: "ML regression model predicting prostate cancer outcomes using clinical biomarker data with interactive Streamlit prediction tool.",
      tags: ["Machine Learning", "Streamlit", "Biomarkers"],
      category: "ML",
      github: null,
    },
    {
      icon: "🌾",
      title: "SAARTHI – Rural Healthcare Platform",
      desc: "Web platform streamlining MBBS intern recruitment and management in rural healthcare facilities across India.",
      tags: ["Web App", "Healthcare", "Management"],
      category: "Web",
      github: null,
    },
    {
      icon: "📝",
      title: "VerbLume – Language Learning App",
      desc: "Learn any language through your own, custom, or base language. Interactive web app with personalized learning modules.",
      tags: ["TypeScript", "EdTech", "Web Dev"],
      category: "Web",
      github: "https://github.com/ganapathi-ai/VerbLume",
    },
    {
      icon: "🤖",
      title: "LinkedIn Content Engine",
      desc: "Intelligent tool to analyze and optimize LinkedIn content for better relevance, engagement, and SEO performance using NLP.",
      tags: ["TypeScript", "NLP", "AI", "Web App"],
      category: "AI",
      github: "https://github.com/ganapathi-ai/LinkedIn-Content-Engine-",
    },
    {
      icon: "📈",
      title: "Stock Price & Sales Forecasting",
      desc: "End-to-end time-series forecasting using Facebook Prophet to predict NSE stock prices and sales. Includes data preprocessing, trend analysis with Pandas, and interactive visualization.",
      tags: ["Python", "Prophet", "Time Series", "Fintech"],
      category: "ML",
      github: null,
    },
    {
      icon: "🛒",
      title: "E-commerce Customer Segmentation",
      desc: "Customer segmentation with clustering and EDA identifying income-spending patterns, plus similarity-based product recommendation system.",
      tags: ["Clustering", "EDA", "Streamlit"],
      category: "ML",
      github: null,
    },
    {
      icon: "📦",
      title: "Product Optimization – Revenue Contribution Analysis",
      desc: "Python-based analysis of product revenue contribution and optimization strategies for business intelligence.",
      tags: ["Python", "Analytics", "Business Intelligence"],
      category: "Analytics",
      github: "https://github.com/ganapathi-ai/Product_Optimization_-_Revenue_Contribution_Analysis",
    },
    {
      icon: "🚢",
      title: "APL Logistics Profitability Intelligence",
      desc: "Profitability intelligence analysis for logistics operations using Python and data analytics.",
      tags: ["Python", "Logistics", "Analytics"],
      category: "Analytics",
      github: "https://github.com/ganapathi-ai/APL_Logistics_Profitability_Intelligence-",
    },
    {
      icon: "🔥",
      title: "Employment Burnout Prediction",
      desc: "Machine learning model to predict employee burnout using workplace and demographic features.",
      tags: ["Python", "ML", "HR Analytics"],
      category: "ML",
      github: null,
    },
    {
      icon: "🎯",
      title: "Recommender System",
      desc: "Collaborative and content-based filtering recommendation engine built with Python.",
      tags: ["Python", "Recommender", "ML"],
      category: "ML",
      github: null,
    },
  ],
  skills: [
    { label: "💻 Programming", items: ["Python", "R", "HTML", "CSS", "JavaScript", "TypeScript"] },
    { label: "📊 Data & BI", items: ["Power BI", "Tableau", "Excel", "PostgreSQL", "Statistics"] },
    { label: "🗄️ Databases", items: ["MongoDB", "Cassandra", "SQL", "PostgreSQL"] },
    { label: "🧠 Machine Learning", items: ["Regression", "Classification", "Clustering", "Time Series", "Survival Analysis"] },
    { label: "🔬 Deep Learning", items: ["Image Segmentation", "CNN", "ResNet", "U-Net"] },
    { label: "⚙️ MLOps", items: ["Streamlit", "Gradio", "Docker", "W&B", "GitHub", "CI/CD Pipelines"] },
    { label: "🤖 AI / GenAI", items: ["RAG", "LangChain", "LlamaIndex", "Vector DBs", "HuggingFace", "GenAI"] },
    { label: "🎨 Design & Dev", items: ["Figma", "Canva", "Jupyter", "VS Code", "Colab", "Anaconda"] },
    { label: "🏷️ Data Annotation", items: ["Image Captioning", "Image Masking", "Video Shot Correction", "Mask MILO"] },
  ],
  certifications: [
    { icon: "🏅", text: "Deep Learning – IIT Ropar (NPTEL, 12 weeks)" },
    { icon: "☁️", text: "AI Fundamentals & the Cloud – AWS" },
    { icon: "🔍", text: "Introduction to AI – Google" },
    { icon: "🤖", text: "Fundamentals of Building AI Agents – IBM" },
    { icon: "📚", text: "Supervised ML: Regression & Classification – DeepLearning.AI & Stanford" },
    { icon: "🗃️", text: "Advanced RAG with Vector Databases – IBM" },
    { icon: "🚀", text: "AI for Digital Readiness & Advancement (ADiRA)" },
    { icon: "🌟", text: "Maximize Productivity With AI Tools – Google" },
    { icon: "🧩", text: "Vector Databases for RAG – IBM" },
    { icon: "🎨", text: "Build Multimodal Generative AI Applications – IBM" },
    { icon: "⚡", text: "Develop Generative AI Applications – IBM" },
    { icon: "🔗", text: "Build RAG Applications – IBM" },
    { icon: "🛠️", text: "AI Tools Workshop" },
  ],
  achievements: [
    { icon: "🏆", text: "Volunteered – 21st International Telemedicine Conference, Bangalore, Nov 2025" },
    { icon: "📡", text: "Student Volunteer – Digital Health Exemplars Seminar, IIHMR, Vijayawada, Dec 2025" },
    { icon: "💡", text: "Bengaluru Tech Summit 2025 Attendee" },
    { icon: "🎖️", text: "Futuristic Leadership Summit 2025 – Bangalore Management Association, Oct 2025" },
  ],
};
